import streamlit as st

_BADGE = {"High": "🟢", "Medium": "🟡", "Low": "⚪"}


def relevance_badge(tier: str) -> str:
    return f"{_BADGE.get(tier, '⚪')} {tier}"


def render_bill_detail(record):
    if not record:
        st.warning("Bill not found.")
        return
    bill = record["bill"]
    st.markdown(f"### {bill.bill_number} — {bill.title}")
    meta_bits = []
    if bill.status:
        meta_bits.append(f"Status: {bill.status}")
    if bill.session_year:
        meta_bits.append(f"Session: {bill.session_year}")
    if meta_bits:
        st.caption("  •  ".join(meta_bits))
    if bill.url:
        st.markdown(f"[View on LegiScan]({bill.url})")
    if bill.subjects:
        st.write("**Subjects:** " + ", ".join(bill.subjects))

    if record.get("summary"):
        st.markdown("#### Summary")
        st.write(record["summary"]["summary_text"])
        model = record["summary"].get("model_used")
        if model:
            st.caption(f"Generated by {model}")
    else:
        st.info(
            "No summary yet. Run `legi-bill summarize --bill "
            f"{bill.bill_number}` to generate one."
        )

    if record.get("questions"):
        st.markdown("#### Compliance questions")
        for q in record["questions"]:
            st.write(f"{q['question_number']}. {q['question_text']}")


def render_empty_db_message():
    st.warning("The Legi-Bill database is empty.")
    st.markdown(
        "Populate it first by running the CLI:\n\n"
        "```bash\n"
        "pip install -r requirements.txt\n"
        "cp .env.example .env   # fill in LEGISCAN_API_KEY and OPENAI_API_KEY\n"
        "python -m legi_bill.cli scrape --session 2025 --limit 30\n"
        "python -m legi_bill.cli summarize --all\n"
        "```\n"
        "Then refresh this page."
    )
